apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coraza-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "coraza-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "coraza-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        {{- if not .Values.openshift.enabled }}
        runAsUser: 65532
        fsGroup: 65532
        {{- end }}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: true
      enableServiceLinks: false
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --leader-elect=true
            - --health-probe-bind-address=:8081
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:8443
            {{- if .Values.metrics.certSecret }}
            - --metrics-cert-path=/etc/metrics-certs
            - --metrics-cert-name={{ .Values.metrics.certName | default "tls.crt" }}
            - --metrics-cert-key={{ .Values.metrics.keyName | default "tls.key" }}
            {{- end }}
            {{- end }}
            - --envoy-cluster-name={{ printf "outbound|80||%s" (include "coraza-operator.serviceFQDN" .) }}
            - --cache-gc-interval=3s
            {{- if .Values.istio.revision }}
            - --istio-revision={{ .Values.istio.revision }}
            {{- end }}
            - --operator-name={{ include "coraza-operator.fullname" . }}
            {{- if .Values.defaultWasmImage }}
            - --default-wasm-image={{ .Values.defaultWasmImage }}
            {{- end }}
            {{- if .Values.logging.development }}
            - --zap-devel=true
            {{- else }}
            - --zap-devel=false
            - --zap-encoder={{ .Values.logging.encoder | default "json" }}
            - --zap-log-level={{ .Values.logging.level | default "info" }}
            - --zap-stacktrace-level={{ .Values.logging.stacktraceLevel | default "error" }}
            - --zap-time-encoding={{ .Values.logging.timeEncoding | default "rfc3339nano" }}
            {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- if .Values.metrics.certSecret }}
          volumeMounts:
            - name: metrics-certs
              mountPath: /etc/metrics-certs
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.resizePolicy }}
          resizePolicy:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.metrics.certSecret }}
      volumes:
        - name: metrics-certs
          secret:
            secretName: {{ .Values.metrics.certSecret }}
      {{- end }}
      serviceAccountName: {{ include "coraza-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
