{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "coraza-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "coraza-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        {{- if and .Values.metrics.certSecret .Values.metrics.caName }}
        ca:
          secret:
            name: {{ .Values.metrics.certSecret }}
            key: {{ .Values.metrics.caName }}
        {{- else }}
        insecureSkipVerify: true
        {{- end }}
{{- end }}