version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directories:
    - "/"
    - "/test/conformance"
    - "/tools/cmd/github_issue_manager"
    schedule:
      day: "monday"
      time: "07:00"
      timezone: "Canada/Eastern"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      all-updates:
        patterns:
          - "*"

  # Dependencies listed in Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - docker
      - dependencies
      - ok-to-test
      - release-note-none
  
  #  Github actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Canada/Eastern"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions-updates:
        patterns:
          - "*"
