{{- define "gvList" -}}
{{- $groupVersions := . -}}
---
title: "API Reference"
linkTitle: "API Reference"
weight: 5
type: docs
description: "Auto-generated API reference for CRDs defined by the Coraza Kubernetes Operator."
---

<!-- This file is auto-generated by crd-ref-docs. Do not edit manually. -->
<!-- Regenerate with: make docs.api -->

## Packages
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
