//go:build conformance

/*
Copyright Coraza Kubernetes Operator contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package conformance

import (
	"io/fs"
	"net/url"
	"os"
	"strconv"
	"testing"
	"time"

	"github.com/bmatcuk/doublestar/v4"
	"github.com/coreruleset/go-ftw/v2/config"
	"github.com/coreruleset/go-ftw/v2/output"
	"github.com/coreruleset/go-ftw/v2/runner"
	"github.com/coreruleset/go-ftw/v2/test"
	"github.com/networking-incubator/coraza-kubernetes-operator/test/framework"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/require"
)

const (
	// rulesetName is the same name generated by hack/generate_coreruleset_configmaps.py
	rulesetName = "default-ruleset"
	// gwName defines the gateway name for this test
	gwName = "gateway-conformance"
)

// TestCoreRuleSetConformance executes a Coreruleset conformance test. It will use the
// project FTW (https://github.com/coreruleset/go-ftw) and the test rules defined by
// coreruleset and execute them against a Gateway with a full RuleSet attached to it.
func TestCoreRuleSetConformance(t *testing.T) {
	ruleLocation := os.Getenv("RULESET_PATH")
	require.NotEmpty(t, ruleLocation, "RULESET_PATH must contain a path for a manifests of RuleSet to be deployed for tests")
	testManifestsLocation := os.Getenv("TESTMANIFESTS_PATH")
	require.NotEmpty(t, testManifestsLocation, "TESTMANIFESTS_PATH must contain the path with the directory containing FTW test manifests")
	configFile := os.Getenv("FTW_CONFIG")
	require.NotEmpty(t, configFile, "FTW_CONFIG must contain the full path for the ftw.yml file")

	_, err := os.Stat(ruleLocation)
	require.NoError(t, err, "RULESET_PATH must be a valid and existing path for the ruleset")
	_, err = os.Stat(configFile)
	require.NoError(t, err, "FTW_CONFIG must be a valid and existing path for the ruleset")

	// Load FTWTests and bail out immediatelly in case of errors
	// TODO, unhardcode the ignore rule processing error
	// -------------------------------------------------------------------------
	// Step 1: Initialize Coreruleset conformance framework
	// -------------------------------------------------------------------------
	tests, err := loadTests(t, testManifestsLocation, true)
	require.NoError(t, err, "error loading FTW tests")
	require.NotZero(t, len(tests), "no test was loaded")

	zerolog.SetGlobalLevel(zerolog.WarnLevel)
	cfg, err := config.NewConfigFromFile(configFile)
	require.NoError(t, err)

	s := fw.NewScenario(t)
	ns := s.GenerateNamespace("crs-conformance")

	// -------------------------------------------------------------------------
	// Step 2: Set up a Gateway for this test
	// -------------------------------------------------------------------------
	s.Step("create gateway")
	s.CreateGateway(ns, gwName)
	s.ExpectGatewayProgrammed(ns, gwName)
	s.Step("deploy echo backend")
	s.CreateEchoBackend(ns, "echo")
	s.CreateHTTPRoute(ns, "echo-route", gwName, "echo")

	// -------------------------------------------------------------------------
	// Step 3: Deploy CRS Coreruleset
	// -------------------------------------------------------------------------
	s.Step("deploy coreruleset-compatible rules")
	// We deploy the ruleset manually based on ruleLocation
	s.ApplyManifest(ns, ruleLocation)
	s.ExpectRuleSetReady(ns, rulesetName)

	// -------------------------------------------------------------------------
	// Step 4: Create Engine targeting the gateway
	// -------------------------------------------------------------------------

	s.Step("create engine")
	s.CreateEngine(ns, "conformance-engine", framework.EngineOpts{
		RuleSetName: rulesetName,
		GatewayName: gwName,
	})

	s.Step("wait for engine ready")
	s.ExpectEngineReady(ns, "conformance-engine")
	s.ExpectWasmPluginExists(ns, "coraza-engine-conformance-engine")

	s.Step("verify operator emitted expected events")
	s.ExpectEvent(ns, framework.EventMatch{Type: "Normal", Reason: "RulesCached"})
	s.ExpectEvent(ns, framework.EventMatch{Type: "Normal", Reason: "WasmPluginCreated"})

	// Give enough time for the engine to load the new rules
	time.Sleep(15 * time.Second)

	// -------------------------------------------------------------------------
	// Step 5: Start logstreaming and proxy, and fix FTW configuration
	// -------------------------------------------------------------------------
	s.Step("start log streaming to file")
	logStream := s.StreamGatewayLogs(ns, gwName)

	// Create temporary file for gateway logs
	logFile, err := os.CreateTemp("", "gateway-logs-*.log")
	require.NoError(t, err, "create temporary log file")

	// Stream logs to file with immediate writes (no buffering)
	logDone := make(chan struct{})
	go func() {
		defer close(logDone)
		buf := make([]byte, 1024)
		totalBytes := 0
		for {
			n, err := logStream.Read(buf)
			if n > 0 {
				totalBytes += n
				_, _ = logFile.Write(buf[:n])
				_ = logFile.Sync() // Force immediate write to disk
			}
			if err != nil {
				if err.Error() != "EOF" {
					t.Logf("log streaming ended: %v (wrote %d bytes)", err, totalBytes)
				} else {
					t.Logf("log streaming completed: wrote %d bytes", totalBytes)
				}
				break
			}
		}
		_ = logFile.Sync() // Final sync before goroutine exits
	}()

	s.OnCleanup(func() {
		<-logDone // Wait for streaming goroutine to finish
		logFile.Close()
		s.T.Logf("Gateway logs saved to: %s", logFile.Name())
	})

	s.Step("initialize proxy to Gateway")
	gw := s.ProxyToGateway(ns, gwName)

	s.Step("override FTW configuration")
	gwUrl, err := url.Parse(gw.URL(""))
	require.NoError(t, err)
	port, err := strconv.Atoi(gwUrl.Port())
	require.NoError(t, err, "invalid port for proxy")
	cfg.LogFile = logFile.Name()
	cfg.TestOverride.Overrides.DestAddr = new(gwUrl.Hostname())
	cfg.TestOverride.Overrides.Port = &port

	// -------------------------------------------------------------------------
	// Step 6: Run FTW tests
	// -------------------------------------------------------------------------
	output := buildOutput(t)
	runnerConfig := config.NewRunnerConfiguration(cfg)
	runnerConfig.ShowTime = false
	runnerConfig.ReadTimeout = 10 * time.Second
	runnerConfig.FailFast = false
	res, err := runner.Run(runnerConfig, tests, output)
	require.NoError(t, err, "error running conformance")

	totalIgnored := len(res.Stats.Ignored)
	if totalIgnored > 0 {
		t.Logf("[info] %d ignored tests: %v", totalIgnored, res.Stats.Ignored)
	}
	totalFailed := len(res.Stats.Failed)
	if totalFailed > 0 {
		t.Errorf("[fatal] %d failed tests: %v", totalFailed, res.Stats.Failed)
	}

}

func loadTests(t *testing.T, manifestDir string, ignoreErrors bool) ([]*test.FTWTest, error) {
	// sample from https://github.com/corazawaf/coraza/blob/main/testing/coreruleset/coreruleset_test.go#L235-L253
	var tests []*test.FTWTest
	fsys := os.DirFS(manifestDir)
	err := doublestar.GlobWalk(fsys, "**/*.yaml", func(path string, d os.DirEntry) error {
		yaml, err := fs.ReadFile(fsys, path)
		if err != nil {
			return err
		}
		ftwt, err := test.GetTestFromYaml(yaml, path)
		if err != nil {
			if !ignoreErrors {
				return err
			}
			t.Logf("an error occurred when processing %s: %s. skipping", path, err)
			return nil
		}
		tests = append(tests, ftwt)
		return nil
	})
	return tests, err
}

func buildOutput(t *testing.T) *output.Output {
	outputFilename := os.Getenv("OUTPUT_FILE")
	outputFormat, ok := os.LookupEnv("OUTPUT_FORMAT")
	if !ok {
		outputFormat = "quiet"
	}

	// use outputFile to write to file
	var outputFile *os.File
	var err error
	if outputFilename == "" {
		outputFile = os.Stdout
	} else {
		outputFile, err = os.Create(outputFilename)
		require.NoError(t, err)
	}
	return output.NewOutput(outputFormat, outputFile)
}
