apiVersion: waf.k8s.coraza.io/v1alpha1
kind: Engine
metadata:
  name: coraza
spec:
  ruleSet:
    name: default-ruleset
  target:
    type: Gateway
    name: coraza-gateway
    provider: Istio
  failurePolicy: fail
