name: Issue Management

permissions: read-all

on:
  issues:
    types:
      [opened, reopened, edited, labeled, unlabeled, milestoned, demilestoned]

jobs:
  manage:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: tools/cmd/github_issue_manager

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: tools/cmd/github_issue_manager/go.mod

      - name: Build issue manager
        working-directory: tools/cmd/github_issue_manager
        run: go build -o "${{ github.workspace }}/github_issue_manager" .

      - name: Close declined issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./github_issue_manager -v \
            --owner "${{ github.repository_owner }}" \
            --repo "${{ github.event.repository.name }}" \
            --issue "${{ github.event.issue.number }}" \
            close-declined

      - name: Update labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./github_issue_manager -v \
            --owner "${{ github.repository_owner }}" \
            --repo "${{ github.event.repository.name }}" \
            --issue "${{ github.event.issue.number }}" \
            update-labels
