name: pr_trigger

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  save-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: echo "${PR_NUMBER}" > pr_number.txt

      - name: upload PR number
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pr-number
          path: pr_number.txt
